---
title: "Untitled"
author: "Maxwel C. Oliveira"
date: "January 18, 2017"
output: html_document
---


```{r loadData, message=FALSE, warning=FALSE, include=FALSE}
Mesot=read.csv("Total.csv")
str(Mesot)
```


```{r LoadPackage drc, warning=FALSE, echo=FALSE, include=FALSE}
library(drc)
```


```{r fit the model, echo=FALSE, warning=FALSE}
Model=drm(ConcX~h, TRT,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Mesot)
summary(Model)
plot(Model, col=c(1,2,3,4,5), ylim=c(0,100))
```


```{r Model selection, warning=FALSE, echo=FALSE, include=FALSE}
mselect(Model, list(LL.3(), AR.2(), LL.5(), W2.3(), l4(), W2.4(), l3())
, nested = FALSE, sorted = c("IC", "Res var", "Lack of fit", "no"), linreg = FALSE, icfct = AIC)
```


```{r, include=FALSE}
library(sandwich)
library(lmtest)
coeftest(Model, vcov = sandwich)
```


```{r, include=FALSE}
library(multcomp)
summary(glht(Model))

```


```{r}
ED(Model, c(50,80), type="absolute", interval="delta")
EDcomp(Model, c(50,50), type="absolute", level=0.95)
```

```{r}
x11()
plot(Full, col=c(1,2,3,4,5), lty=1, pch=16, ylim=c(0,100), type="confidence", legendPos=c(200,20), ylab = "Mesotrione Metabolism in Waterhemp (%)", xlab = expression(paste("Hours after herbicide application")))

```



```{r}

par(mar=c(5,6,1,1), mgp=c(3.0,1,0))
plot(Model, col=c(1,2,3,4,5), lty=1, pch=16, cex=1.2, lwd=5, broken=F, axes=F, ylim=c(0,100), cex.lab = 1.4, legend="", type="none", cex.lab=1.6,
     ylab = "Mesotrione Metabolism in Waterhemp (%)", 
     xlab = expression(paste("Hours after herbicide application")))

legend ("bottomright", legend= c ("Amitrole fb Mesotrione-R", "Malathion fb Mesotrione-R", "PBO fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S"), col=c(1,2,3,4,5), cex=1.5, lty=c(1,1,1,1,1), lwd=5, bty="n")

axis(side=2, font = 1,  las=1, at = seq(0,100, by=20), cex.axis=1.8)
axis(side=1, font = 1, at = c(0, 12, 24, 72, 168,336), cex.axis=1.8)
```



```{r, include=FALSE}
Mesot$TRTB <-factor(Mesot$TRT, levels=c("Aminotriazole", "Malathion", "Piperonyl butoxide", "R", "S"), labels=c("Aminotriozole fb Mesotrione-R", "Malathion fb Mesotrione-R", "Piperonyl butoxide fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S"))
str(Mesot)


library(drc)
Full=drm(ConcX~h, TRTB,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Mesot)
summary(Full)

EDcomp(Full, c(90,90), type="absolute", level=0.95)
ED(Full, c(80), type="absolute")



# predictions and confidence intervals
newdata <- expand.grid(h=exp(seq(0, 366, 1)))
newdata <- data.frame(h=seq(0,336, 1))
newdata1 <- data.frame(TRTB=c("Aminotriozole fb Mesotrione-R"), newdata)
newdata2 <- data.frame(TRTB=c("Malathion fb Mesotrione-R"), newdata)
newdata3 <- data.frame(TRTB=c("Piperonyl butoxide fb Mesotrione-R"), newdata)
newdata4 <- data.frame(TRTB=c("Mesotrione-R"), newdata)
newdata5 <- data.frame(TRTB=c("Mesotrione-S"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4, newdata5)

pm <- predict(Full, newdata=nd, interval="confidence") 
nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 
```



```{r, echo=FALSE}
library(ggplot2)
x11()
ggplot(Mesot, aes(x = h, y = y)) + ggtitle("Mesotrione Metabolism in Waterhemp Leaves") + #geom_point(aes(shape=TRTB, col=TRTB), size=2) +
 coord_cartesian(ylim = c(0, 100)) + labs(fill="", y="Mesotrione Metabolism (%)", x="Hours After Treatment") +
geom_line(data=nd, aes(x=h, y=p, col=TRTB), size=3) +
#geom_ribbon(data=nd, aes(x=h, y=p, ymin=pmin, ymax=pmax, fill=TRTB), alpha=0.5)  + 
  scale_color_brewer(palette="Set1") +
  scale_x_continuous(breaks = c(0,24,72,168, 336)) +
theme(axis.text=element_text(size=25, color="black"), 
        axis.title=element_text(size=30,face="bold"), 
        panel.background = element_rect(color = "black"), 
        panel.grid.major = element_line(color = "white"), 
    panel.grid.minor = element_blank(),
       legend.position=c(0.68,0.4), legend.text = element_text(size = 20, colour = "black", face="bold"), 
    legend.background = element_rect(color = "black"), plot.title =  element_text(size=30, hjust = 0.5, color="blue", face="italic"), legend.title=element_blank(), legend.key = element_rect(size = 4),
        legend.key.size = unit(2, 'lines'))  
```

```{r}
ED(Full, c(50), type="absolute", interval="delta")
EDcomp(Full, c(50,50), type="absolute", level=0.95)
```





```{r}
library(ggplot2)

Herbicide<-data.frame(trt=c("Aminotriozole fb Mesotrione-R", "Malathion fb Mesotrione-R", "Piperonyl butoxide fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S"), y=c(31.08, 19.21, 22.89, 19.89, 48.87), se=c(2.03, 1.39, 1.12, 1.12, 8.09))
limits <- aes(ymax = y + se, ymin=y - se) 

Herbicide$trt <- factor(Herbicide$trt, levels = c("Aminotriozole fb Mesotrione-R", "Malathion fb Mesotrione-R", "Piperonyl butoxide fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S")) 





ggplot(Herbicide, aes(fill=trt, x=trt, y=y)) + ggtitle("50% Mesotrione Metabolism in Waterhemp Leaves") + geom_bar(position="dodge", stat="identity", color="black") + geom_errorbar(limits, width=0.25, col="white") + 
  labs(y="Hours After Treatment", x="") + scale_y_continuous(limits=c(0, 65))+
  theme(axis.text=element_text(size=25, color="black"), 
        axis.title=element_text(size=30,face="bold"), 
        panel.background = element_rect(fill= "black"), 
        panel.grid.major = element_line(color = "black"), 
    panel.grid.minor = element_blank(), legend.key.size = unit(2, 'lines'),
       legend.position=c(0.26,0.87), legend.text = element_text(size = 20, colour = "black", face = "bold"), 
    axis.text.x=element_blank(), axis.ticks.x=element_blank(),
    legend.background = element_rect(colour = "black"), plot.title =  element_text(size=30, hjust=0.5, color="blue", face="italic"), legend.title=element_blank()) + scale_fill_brewer(palette="Set1")
```



```{r}
library(ggplot2)

Data<-data.frame(trt=c("Aminotriozole fb Mesotrione-R", "Malathion fb Mesotrione-R", "Piperonyl butoxide fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S"), resp=c(48.1, 26.1, 36.2, 27.1, 149.1), se=c(7.47, 1.54, 3.84, 1.64, 47.7))
limits <- aes(ymax = resp + se, ymin=resp - se)

Data$trt <- factor(Data$trt, levels = c("Aminotriozole fb Mesotrione-R", "Malathion fb Mesotrione-R", "Piperonyl butoxide fb Mesotrione-R", "Mesotrione-R", "Mesotrione-S"))

ggplot(Data, aes(fill=trt, x=trt, y=resp)) + ggtitle("80% Mesotrione Metabolism in Waterhemp Leaves") + geom_bar(position="dodge", stat="identity", color="black") + geom_errorbar(limits, width=0.25, col= "white") + 
  labs(y="Hours After Treatment", x="") + scale_y_continuous(limits=c(0,230)) +
  theme(axis.text=element_text(size=25, color="black"), 
        axis.title=element_text(size=30,face="bold"), 
        panel.background = element_rect(fill = "black"), 
        panel.grid.major = element_line(color = "black"), 
    panel.grid.minor = element_blank(), legend.key.size = unit(2, 'lines'),
       legend.position=c(0.26,0.87), legend.text = element_text(size = 20, colour = "black", face = "bold"), 
    axis.text.x=element_blank(), axis.ticks.x=element_blank(),
    legend.background = element_rect(colour = "black"), plot.title =  element_text(size=30, hjust=0.5, color="blue", face="italic"), legend.title=element_blank()) + scale_fill_brewer(palette="Set1")
```

