---
title: "Meso_Paper"
author: "Maxwel C. Oliveira"
date: "February 10, 2017"
output: html_document
---


```{r loadData, message=FALSE, warning=FALSE, include=FALSE}
Mesot=read.csv("Total.csv")
str(Mesot)
```


```{r LoadPackage drc, warning=FALSE, echo=FALSE, include=FALSE}
library(drc)
library(ggplot2)
library(gridExtra)
library(cowplot)
```


```{r fit the model, echo=FALSE, warning=FALSE}
Model=drm(y~h, TRT,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Mesot)
summary(Model)
plot(Model)
```


```{r Model selection, warning=FALSE, echo=FALSE, include=FALSE}
mselect(Model, list(LL.3(), AR.3(), LL.5(), W2.3(), l4(), W2.4(), l3())
, nested = FALSE, sorted = c("IC", "Res var", "Lack of fit", "no"), linreg = FALSE, icfct = AIC)
```



```{r}
ED(Model, c(50,90), type="absolute", interval="delta")
EDcomp(Model, c(50,50), type="absolute", level=0.95)
```


```{r, include=FALSE}
Mesot$TRTB <-factor(Mesot$TRT, levels=c("Aminotriazole", "Malathion", "Piperonyl butoxide", "R", "S"), labels=c("amitrole fb mesotrione-R", "malathion fb mesotrione-R", "piperonyl butoxide fb mesotrione-R", "mesotrione-R", "mesotrione-S"))
str(Mesot)


library(drc)
Full=drm(y~h, TRTB,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Mesot)
summary(Full)
#plot(Full)


EDcomp(Full, c(90,90), type="absolute", level=0.95)
ED(Full, c(80), type="absolute")
EDcomp(Full, c(50,50), type="absolute")


# predictions and confidence intervals
newdata <- expand.grid(h=exp(seq(log(0.5), log(336), length=336)))
#newdata <- data.frame(h=exp(seq(log(0.5), log(100), length=100)))
newdata1 <- data.frame(TRTB=c("amitrole fb mesotrione-R"), newdata)
newdata2 <- data.frame(TRTB=c("malathion fb mesotrione-R"), newdata)
newdata3 <- data.frame(TRTB=c("piperonyl butoxide fb mesotrione-R"), newdata)
newdata4 <- data.frame(TRTB=c("mesotrione-R"), newdata)
newdata5 <- data.frame(TRTB=c("mesotrione-S"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4, newdata5)

pm <- predict(Full, newdata=nd, interval="confidence")


nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 


Mesot$h0 <- Mesot$h
Mesot$h0[Mesot$h0==0] <- 0.5
```



```{r, echo=FALSE}
library(ggplot2)
A<-ggplot(Mesot, aes(x = h0, y = y)) +  
geom_line(data=nd, aes(x=h, y=p, linetype=TRTB, color=TRTB), size=1.3) + coord_trans(x="log") +
  labs(fill="", y="Mesotrione metabolism (%)", x="Hours after treatment") + 
  scale_colour_manual(values = c("red","blue", "green", "black", "grey70"))+
  scale_x_continuous(breaks=c(12, 24, 72, 168, 336), limits=c(12,336)) +
  theme(axis.text=element_text(size=16, color="black"), 
        axis.title=element_text(size=18,face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(),
  legend.position=c(0.66,0.15), legend.text = element_text(size = 13, colour = "black"), legend.key = element_rect(fill=NA), panel.border = element_rect(fill=NA,color="black", size=0.5, 
                                    linetype="solid"),
legend.background = element_rect(fill =NA), legend.key.width = unit(2.2, "line"), legend.title=element_blank())  + ylim(0,100) +
ggsave("Mesotrione1.tiff", units="in", width=6, height=6, dpi=500)
A
```

```{r}
ED(Full, c(50), type="absolute", interval="delta")
EDcomp(Full, c(50,50))
```














```{r LoadPackage drc, warning=FALSE, echo=FALSE, include=FALSE}
library(drc)
```


```{r loadData, message=FALSE, warning=FALSE, include=FALSE}
Tembo=read.csv("Tembotrione.csv")
str(Tembo)
```



```{r fit the model, echo=FALSE, warning=FALSE}
Model=drm(y~h, TRT,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Tembo)
summary(Model)
plot(Model, col=c(1,2,3,4,5))
```

```{r Model selection, warning=FALSE, echo=FALSE, include=FALSE}
mselect(Model, list(LL.3(), LL.5(), W1.3(), l4(), W2.4(), l3())
, nested = FALSE, sorted = c("IC", "Res var", "Lack of fit", "no"), linreg = FALSE, icfct = AIC)
```

```{r}
ED(Model, c(50), type="absolute", interval="delta")
EDcomp(Model, c(80,80), type="absolute", level=0.95)
```


```{r, include=FALSE}
Tembo$TRTB <-factor(Tembo$TRT, levels=c("Aminotriozole", "Malathion", "Piperonyl butoxide", "R", "S"), labels=c("amitrole fb tembotrione-R", "malathion fb tembotrione-R", "piperonyl butoxide fb tembotrione-R", "tembotrione-R", "tembotrione-S"))
str(Tembo)

Model=drm(y~h, TRTB,  fct=W1.3 (fixed =c(NA,NA,NA)), data= Tembo)
ED(Model, c(80), type="absolute", interval = "delta")
EDcomp(Model, c(50,50), type="absolute")

# predictions and confidence intervals
newdata <- expand.grid(h=exp(seq(log(0.5), log(336), length=336)))
#newdata <- data.frame(h=seq(0,336, 1))
newdata6 <- data.frame(TRTB=c("amitrole fb tembotrione-R"), newdata)
newdata7 <- data.frame(TRTB=c("malathion fb tembotrione-R"), newdata)
newdata8 <- data.frame(TRTB=c("piperonyl butoxide fb tembotrione-R"), newdata)
newdata9 <- data.frame(TRTB=c("tembotrione-R"), newdata)
newdata10 <- data.frame(TRTB=c("tembotrione-S"), newdata)

nd=rbind(newdata6, newdata7, newdata8, newdata9, newdata10)

pm <- predict(Model, newdata=nd, interval="confidence") 
nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

Tembo$h0 <- Tembo$h
Tembo$h0[Tembo$h0==0] <- 0.5
```


```{r, echo=FALSE}
library(ggplot2)
B<-ggplot(Tembo, aes(x = h0, y = y)) +  
geom_line(data=nd, aes(x=h, y=p, linetype=TRTB, color=TRTB), size=1.3) + coord_trans(x="log") + #scale_color_brewer(palette="Set1") +
  labs(fill="", y="Tembotrione metabolism (%)", x="Hours after treatment") +
   scale_colour_manual(values = c("red","blue", "green", "black", "grey70"))+
  scale_x_continuous(breaks=c(12, 24, 72, 168, 336), limits=c(12,336)) +
  theme(axis.text=element_text(size=16, color="black"), 
        axis.title=element_text(size=18,face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(),
  legend.position=c(0.66,0.15), legend.text = element_text(size = 13, colour = "black"), legend.key = element_rect(fill=NA), panel.border = element_rect(fill=NA,color="black", size=0.5, 
                                    linetype="solid"),
legend.background = element_rect(fill =NA), legend.key.width = unit(2.2, "line"), legend.title=element_blank())  + ylim(0,100) +
ggsave("Tembot.tiff", units="in", width=6, height=6, dpi=500)
```



```{r vertical, include=FALSE}
plot_grid(A,B, ncol=2, labels = c("(A)", "(B)"), label_size = 18,
          hjust = 0, vjust = 1.5) + ggsave("allhor.tiff",  units="in", width=12, height=6, dpi=2000)
```



