---
title: "Field work"
author: "Maxwel C. Oliveira"
date: "May 22, 2017"
output: html_document
---

```{r, include=FALSE}
library(drc)
library(ggplot2)
library(cowplot)
library(lmtest)
library(sandwich)
library(multcomp)
```



```{r loadData, warning=F}
Data=read.csv("Data.csv")
str(Data)
```



```{r}
M=drm(IR~RateM, Herbicide, fct=W1.3(), data=Data)
plot(M)
summary(M)
compParm(Control, "e")
```

```{r}
Control=drm(IR~RateM, Herbicide,  fct=l3(fixed =c(NA,100,NA)), data= Data)


coeftest(Control, vcov = sandwich)
summary(glht(Control))
ED(Control, c(50))
EDcomp(Control, c(50,50))
```


```{r Control, warning=FALSE}
Control=drm(IR~RateM, Herbicide,  fct=l3 (fixed =c(NA,100,NA)), data= Data)
summary(Control)

mselect(Control,
list(l4(), l3(), W1.4(), W2.3(), FPL.4(-1,1), FPL.4(-2,3), FPL.4(-0.5,0.5)))



# predictions and confidence intervals
newdata <- expand.grid(RateM=seq(0,850))

newdata1 <- data.frame(Herbicide=c("mesotrione"), newdata)
newdata2 <- data.frame(Herbicide=c("malathion fb mesotrione"), newdata)


nd=rbind(newdata1, newdata2)

pm <- predict(Control, newdata=nd, interval="confidence")


nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 




A=ggplot(Data, aes(x = RateM, y = IR)) +  
geom_line(data=nd, aes(x=RateM, y=p, linetype=Herbicide, color=Herbicide), size=1.3) +
  labs(fill="", y="Control (%)", x=expression(bold(paste("Mesotrione (g ai ha "^"-1",")")))) +
  scale_colour_manual(values = c("red", "black"))+
  scale_x_continuous(breaks=c(0, 105, 210, 420, 840)) +
  theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
                                    linetype="solid"), 
  legend.position=c(0.30,0.95), legend.text = element_text(size = 16, colour = "black"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  + ylim(0,100) + ggsave("Control.tiff", units="in", width=6, height=6, dpi=300)

```

```{r}
plot(Control)
abline(h=50, v=142.40706)
```





```{r Biomass, warning=FALSE}
Biomass=drm(Biomass~RateM, Herbicide, fct=l3 (fixed =c(NA,NA,NA)), data= Data)
summary(Biomass)

mselect(Biomass,
list(l4(), l3(), W1.4(), W2.3(), FPL.4(-1,1), FPL.4(-2,3), FPL.4(-0.5,0.5)))

# predictions and confidence intervals
newdata <- expand.grid(RateM=seq(0,850))

newdata1 <- data.frame(Herbicide=c("mesotrione"), newdata)
newdata2 <- data.frame(Herbicide=c("malathion fb mesotrione"), newdata)


nd=rbind(newdata1, newdata2)

pm <- predict(Biomass, newdata=nd, interval="confidence")


nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 




B=ggplot(Data, aes(x = RateM, y = Biomass)) +  
geom_line(data=nd, aes(x=RateM, y=p, linetype=Herbicide, color=Herbicide), size=1.3) + #geom_ribbon(data=nd, aes(x=RateM, y=p, ymin=pmin, ymax=pmax), alpha=0.1) +
  labs(fill="", y=expression(bold(paste("Biomass (g m "^"-2",")"))), x=expression(bold(paste("Mesotrione (g ai ha "^"-1",")")))) +
  scale_colour_manual(values = c("red", "black"))+
  scale_x_continuous(breaks=c(0, 105, 210, 420, 840)) +
  theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
                                    linetype="solid"), 
  legend.position=c(0.68,0.95), legend.text = element_text(size = 16, colour = "black"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  + ylim(0,250) + ggsave("Biomass.tiff", units="in", width=6, height=6, dpi=300)
```


```{r horiz, include=FALSE}
plot_grid(A,B, ncol=1) + ggsave("allv.tiff", units="in", width=6, height=12, dpi=300)
```

```{r vertical, include=FALSE}
plot_grid(A,B, ncol=2, labels = c("A", "B"), label_size = 18,
          hjust = -1, vjust = 1.5) + ggsave("allhor.tiff",  units="in", width=12, height=6, dpi=1000)
```



```{r}
ED(Control, c(50))
EDcomp(Control, c(50,50))
```


```{r}
ED(Biomass, c(50, 80), type="relative")
EDcomp(Biomass, c(50,50))
```


```{r Biomass, warning=FALSE}
Number=drm(Number~RateM, Herbicide, fct=l3 (fixed =c(NA,NA,NA)), data= Data)
summary(Number)



# predictions and confidence intervals
newdata <- expand.grid(RateM=seq(0,850))

newdata1 <- data.frame(Herbicide=c("mesotrione"), newdata)
newdata2 <- data.frame(Herbicide=c("malathion fb mesotrione"), newdata)


nd=rbind(newdata1, newdata2)

pm <- predict(Number, newdata=nd, interval="confidence")


nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 




C=ggplot(Data, aes(x = RateM, y = Number)) +  
geom_line(data=nd, aes(x=RateM, y=p, linetype=Herbicide, color=Herbicide), size=1.3) + #geom_ribbon(data=nd, aes(x=RateM, y=p, ymin=pmin, ymax=pmax), alpha=0.1) +
  labs(fill="", y=expression(bold(paste("Density (plants m "^"-2",")"))), x=expression(bold(paste("Mesotrione (g ai ha "^"-1",")")))) +
  scale_colour_manual(values = c("red", "black"))+
  scale_x_continuous(breaks=c(0, 105, 210, 420, 840)) +
  theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
                                    linetype="solid"), 
  legend.position=c(9.30,9.95), legend.text = element_text(size = 16, colour = "black"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  + ylim(0,400) + ggsave("Plants.tiff", units="in", width=6, height=6, dpi=300)
```

```{r}
ED(Number, c(50, 80))
EDcomp(Number, c(50,50))
```


```{r vertical, include=FALSE}
plot_grid(B,C, ncol=2, labels = c("A", "B"), label_size = 18,
          hjust = -1, vjust = 1.5) + ggsave("allhor.tiff",  units="in", width=12, height=6, dpi=1000)
```


