---
title: "Topromezone"
author: "Maxwel C. Oliveira"
date: "November 10, 2016"
output: word_document
---

```{r}
library(ggplot2)

```

```{r}
Data=read.csv("biomass.csv")
Data$TRT=as.factor(Data$TRT)
str(Data)
```


```{r, echo=FALSE}
Topro<-Data[(Data$Group3 == 'Topro'),]
str(Topro)
```

```{r}
X11()
ggplot(Topro, aes(y=Biomass, x=TRT)) + geom_boxplot(aes(fill=factor(TRT))) + labs(fill="TRT", x="", y= expression(paste("HPPD-R Waterhemp Biomass (g m "^"-2",")"))) + scale_y_continuous(limits=c(0, 300)) + scale_fill_discrete(labels = c("Control", "Tembotrione", "Malathion fb Tembotrione", "Amitrole fb Tembotrione", "PBO fb Tembotrione"))  +  
  theme(axis.text=element_text(size=23, color="black"),  axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title=element_text(size=23,face="bold"), legend.text = element_text(colour="black", size = 17, face = "bold"), legend.position=c(0.7,0.8), legend.background = element_rect(fill="white", size=.5, linetype="dotted"))  +
  theme(legend.title=element_blank())
```
